# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -V verify -Dmaven.javadoc.skip=true --file pom.xml
    - name: Archive JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          target/flight-spark-source-1.0-SNAPSHOT-shaded.jar
